name: rust-release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      bin: gram

                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      bin: gram.exe

                    - os: macos-latest
                      target: x86_64-apple-darwin
                      bin: gram

                    - os: macos-latest
                      target: aarch64-apple-darwin
                      bin: gram
        runs-on: ${{ matrix.os }}


        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Rust Nightly
              uses: dtolnay/rust-toolchain@nightly
              with:
                  targets: ${{ matrix.target }}

            - name: Install dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                  cmake \
                  g++ \
                  make \
                  gperf \
                  perl \
                  pkg-config \
                  libssl-dev \
                  zlib1g-dev

            - name: Install dependencies (macOS)
              if: runner.os == 'macOS'
              run: |
                  brew install cmake gperf openssl pkg-config

            - name: Install dependencies (Windows)
                  if: runner.os == 'Windows'
                  run: |
                      winget install Kitware.CMake

            - name: Build TDLib
              run: |
                cd td_api/td
                mkdir -p build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release
                cmake --build . -j 4

            - name: Build
              run: cargo build --release --target ${{ matrix.target }}

            - name: Prepare artifact (unix)
              if: runner.os != 'Windows'
              run: |
                  mkdir -p dist
                  cp target/${{ matrix.target }}/release/${{ matrix.bin }} dist/${{ matrix.bin }}-${{ matrix.target }}

            - name: Prepare artifact (windows)
              if: runner.os == 'Windows'
              run: |
                  mkdir dist
                  copy target\${{ matrix.target }}\release\${{ matrix.bin }} dist\${{ matrix.bin }}-${{ matrix.target }}.exe

            - name: Upload release assets
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*
              env:
                  GITHUB_TOKEN: ${{ secrets.ghtoken }}
